name: run e2e tests

on:
  push:
    branches: 
      'feature/*'
      
jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout
        uses: actions/checkout@v3.3.0
        
      - name: run e2e test
        run: cypress test
